version: "3"

tasks:
  check:
    desc: Exist gradle and dependences
    run: once
    deps:
      - task: check:gradle

  check:gradle:
    desc: Exist gradlew
    run: once
    preconditions:
      - sh: command -v ./gradlew
        msg: "Please Install gradle"

  setup:
    desc: Setup gradle dependences.
    run: once
    cmds:
      - ./gradlew clean install
    deps:
      - task: check:gradle

  dependencies:
    desc: Setup gradle dependencies.
    run: once
    cmds:
      - ./gradlew dependencies
    deps:
      - task: check:gradle

  clean:
    desc: Clean gradle packages.
    run: once
    cmds:
      - ./gradlew clean
    deps:
      - task: check:gradle

  build:
    desc: Build gradle packages.
    run: once
    cmds:
      - ./gradlew clean build
    deps:
      - task: check:gradle

  test:
    desc: Test gradle packages.
    cmds:
      - ./gradlew clean test
    deps:
      - task: check:gradle

  test:allure:
    desc: Test gradle run allureServe
    cmds:
      - ./gradlew clean test allureServe
    deps:
      - task: check:gradle

  run:
    desc: Run gradle.
    run: once
    cmds:
      - ./gradlew bootRun
    deps:
      - task: check:gradle

  publish:
    desc: Publish gradle packages.
    run: once
    cmds:
      - ./gradlew publish
    deps:
      - task: check:gradle
