version: "3"

vars:
  GRADLE_VERSION: 8.14

tasks:
  check:
    desc: Exist gradle and dependences
    run: once
    deps:
      - task: check:gradle

  check:gradle:
    desc: Exist gradlew
    run: once
    preconditions:
      - sh: command -v ./gradlew
        msg: "Please Install gradle"

  setup:
    desc: Setup gradle dependences.
    run: once
    cmds:
      - ./gradlew clean install
    deps:
      - task: check:gradle

  dependencies:
    desc: Setup gradle dependencies.
    run: once
    cmds:
      - ./gradlew dependencies
    deps:
      - task: check:gradle

  clean:
    desc: Clean gradle packages.
    run: once
    cmds:
      - ./gradlew clean
    deps:
      - task: check:gradle

  build:
    desc: Build gradle packages.
    run: once
    cmds:
      - ./gradlew clean build
    deps:
      - task: check:gradle

  test:
    desc: Test gradle packages.
    cmds:
      - ./gradlew clean test
    deps:
      - task: check:gradle

  test:allure:
    desc: Test gradle run allureServe
    cmds:
      - ./gradlew clean test allureServe
    deps:
      - task: check:gradle

  run:
    desc: Run gradle.
    run: once
    cmds:
      - ./gradlew bootRun
    deps:
      - task: check:gradle

  publish:
    desc: Publish gradle packages.
    run: once
    cmds:
      - ./gradlew publish
    deps:
      - task: check:gradle

  environment:
    desc: Generate environment Gradle
    run: once
    cmds:
      - mkdir -p gradle/wrapper
      - curl -o gradlew https://raw.githubusercontent.com/gradle/gradle/master/gradle/wrapper/gradlew
      - curl -o gradlew.bat https://raw.githubusercontent.com/gradle/gradle/master/gradle/wrapper/gradlew.bat
      - curl -o gradle/wrapper/gradle-wrapper.jar https://services.gradle.org/distributions/gradle-wrapper.jar
      - curl -o gradle/wrapper/gradle-wrapper.properties https://raw.githubusercontent.com/gradle/gradle/v{{ .GRADLE_VERSION }}/gradle/wrapper/gradle-wrapper.properties
      - chmod +x gradlew
