version: "3"

vars:
  GRADLE_VERSION: 8.14

tasks:
  check:
    desc: Exist android and dependences
    run: once
    deps:
      - task: check:gradle
      - task: check:vars

  check:vars:
    desc: Exist vars of android
    run: once
    preconditions:
      - sh: test -v ANDROID_HOME
        msg: "Please add var environment ANDROID_HOME"

  check:gradle:
    desc: Exist gradlew
    run: once
    preconditions:
      - sh: command -v ./gradlew
        msg: "Please Install gradle"

  setup:
    desc: Setup gradle dependences.
    run: once
    cmds:
      - ./gradlew clean install
    deps:
      - task: check:gradle

  fmt:
    desc: fmt
    cmds:
      - ./gradlew ktlintFormat
    deps:
      - task: check:gradle

  lint:
    desc: Run linter.
    run: once
    cmds:
      - ./gradlew ktlintCheck
    deps:
      - task: check:gradle

  fix:
    desc: Fix lint violations.
    run: once
    cmds:
      - ./gradlew ktlintFormat
    deps:
      - task: check:gradle

  dependencies:
    desc: Setup gradle dependencies.
    run: once
    cmds:
      - ./gradlew dependencies
    deps:
      - task: check:gradle

  clean:
    desc: Clean gradle packages.
    run: once
    cmds:
      - ./gradlew clean
    deps:
      - task: check:gradle

  build:
    desc: Build gradle packages.
    run: once
    cmds:
      - ./gradlew clean build
    deps:
      - task: check:gradle

  test:
    desc: Test gradle packages.
    cmds:
      - ./gradlew clean test
    deps:
      - task: check:gradle

  test:allure:
    desc: Test gradle run allureServe
    cmds:
      - ./gradlew clean test allureServe
    deps:
      - task: check:gradle

  run:
    desc: Run gradle.
    run: once
    cmds:
      - ./gradlew bootRun
    deps:
      - task: check:gradle

  publish:
    desc: Publish gradle packages.
    run: once
    cmds:
      - ./gradlew publish
    deps:
      - task: check:gradle