version: "3"

tasks:
  _changelog_next:
    internal: true
    cmds:
      - cmd: task changelog:next APP_TAG=$({{.PYTHON_PACKAGE_MANAGER}} run bump-my-version show current_version)

  major:
    desc: Release major (version bump + next changelog)
    cmds:
      - task: version:major
      - task: _changelog_next

  minor:
    desc: Release minor (version bump + next changelog)
    cmds:
      - task: version:minor
      - task: _changelog_next

  patch:
    desc: Release patch (version bump + next changelog)
    cmds:
      - task: version:patch
      - task: _changelog_next

  pre_release:
    desc: Release pre-release (version bump + next changelog)
    cmds:
      - task: version:pre_release
      - task: _changelog_next
